### ISSUE TITLE
phantomjs now requires `brew cask install`

### ISSUE THREAD

**Issue by sarahlim** [Khan/khan-dotfiles#16]
Running the installation script on macOS High Sierra eventually gives the following error:

```
  [ .. ] Checking for phantomjs
Error: No available formula with the name "phantomjs"
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install phantomjs
make[1]: *** [os-install] Error 1
make: *** [install] Error 2
```

Changing the following line: https://github.com/Khan/khan-dotfiles/blob/f6acfa52cdb23a7077b3ca29e0abf331b7bc320c/mac-setup.sh#L280 to
```sh
brew cask install phantomjs
```
fixed the problem for me.

**Comment by csilvers** [comment]
Thanks!  Would be great if you could make a pull request.

**Comment by sarahlim** [comment]
Sure, via GitHub or Phabricator?

**Comment by csilvers** [comment]
Phab is preferable!
